{{
  config(
    materialized='table',
    type='streaming',
    pre_hook=[
      "DROP TABLE IF EXISTS default_catalog.default_database.contractor_source",
      "CREATE TABLE default_catalog.default_database.contractor_source (
        `ВерсияДанных` STRING,
        `DeletionMark` STRING,
        `UID` VARCHAR(50),
        `GUID` VARCHAR(50),
        `Name` STRING,
        `Code` STRING,
        `Parent` STRING,
        `IsGroupe` STRING,
        `src_change_timestamp` STRING,
        `extract_timestamp` STRING,
        `operation_type` STRING,
        `rc_AdresMezhdunarodnyy` STRING,
        `rc_VidGosudarstvennogoOrgana` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_VidKontragentaDlyaVGO` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_GorodStranaMezhdunarodnyy` STRING,
        `rc_GosudarstvennyyOrgan` STRING,
        `rc_GruppaKontragenta` STRING,
        `rc_DataPostanovkiNaUchetVNalogovoy` STRING,
        `rc_DataRozhdeniya` STRING,
        `rc_DULNomer` STRING,
        `rc_DULSeriya` STRING,
        `rc_Imya` STRING,
        `rc_IndividualnyyPredprinimatel` STRING,
        `rc_IspolzovatProgrammuZakupok` STRING,
        `rc_KanalProdazh` STRING,
        `rc_KodGosudarstvennogoOrgana` STRING,
        `rc_KodOKVED` STRING,
        `rc_KodOKVED2` STRING,
        `rc_KodOKFS` STRING,
        `rc_KodPoOKTMO` STRING,
        `rc_OsnovnoeKontaktnoeLitso` STRING,
        `rc_OsnovnoeKontaktnoeLitsoVIFNS` STRING,
        `rc_OsnovnoyBankovskiySchet` STRING,
        `rc_Otchestvo` STRING,
        `rc_PodrazdeleniePoOrgShtatnoyStrukture` STRING,
        `rc_PodrazdeleniePoUpravlencheskoyStrukture` STRING,
        `rc_Pol` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_PriznakMeditsinskoyOrganizatsii` STRING,
        `rc_Samozanyatyy` STRING,
        `rc_SvidetelstvoDataVydachi` STRING,
        `rc_SvidetelstvoSeriyaNomer` STRING,
        `rc_SNILS` STRING,
        `rc_SubektMalogoIliSrednegoPredprinimatelstvaUKh` STRING,
        `rc_Familiya` STRING,
        `rc_FIOIDolzhnostRukovoditelya` STRING,
        `rc_FIOIDolzhnostRukovoditelyaVRoditelnomPadezhe` STRING,
        `rc_FormaUchastiyaVKapitale` STRING,
        `rc_EtoBank` STRING,
        `rc_EtoStrakhovayaKompaniya` STRING,
        `rc_YuridicheskoeFizicheskoeLitso` ROW<`Тип1С` STRING, `Значение` STRING>,
        `GolovnoyKontragent` STRING,
        `DokumentUdostoveryayushchiyLichnost` STRING,
        `Identifikator` STRING,
        `INN` STRING,
        `KodOKOPF` STRING,
        `KodPoOKPO` STRING,
        `Kommentariy` STRING,
        `KPP` STRING,
        `MezhdunarodnoeNaimenovanie` STRING,
        `NaborSvoystv` STRING,
        `NaimenovanieOKOPF` STRING,
        `NalogovyyNomer` STRING,
        `Nerezident` STRING,
        `ObosoblennoePodrazdelenie` STRING,
        `OGRN` STRING,
        `OKDP` STRING,
        `Opisanie` STRING,
        `OrganizatsionnayaEdinitsa` STRING,
        `OrganizatsionnoPravovayaForma` STRING,
        `Partner` STRING,
        `PolnoeNaimenovanie` STRING,
        `PriznakIspolzovaniya` ROW<`Тип1С` STRING, `Значение` STRING>,
        `RegistratsionnyyNomerNerezidenta` STRING,
        `SokrashchennoeNaimenovanie` STRING,
        `StranaRegistratsii` STRING,
        `UdalitZapisNeNormalizuema` STRING,
        `UdalitTipPozitsii` ROW<`Тип1С` STRING, `Значение` STRING>,
        `UdalitEtalonnayaPozitsiya` STRING,
        `UdalitEtoMaket` STRING,
        `YurFizLitso` ROW<`Тип1С` STRING, `Значение` STRING>,
        `OsnovnoyBankovskiySchet` STRING,
        `Version` VARCHAR(10),
        `VersionDate` STRING
      ) WITH (
        'connector' = 'kafka',
        'topic' = 'sys__nsi__esud_rzdm__contractor__data',
        'properties.bootstrap.servers' = '{{ kafka_bootstrap_servers() }}',
        'properties.security.protocol' = '{{ kafka_security_protocol() }}',
        'properties.sasl.mechanism' = '{{ kafka_sasl_mechanism() }}',
        'properties.sasl.jaas.config' = '{{ kafka_sasl_jaas_config() }}',
        'properties.group.id' = 'dbt-nsi-contractor',
        'scan.startup.mode' = 'group-offsets',
        'properties.auto.offset.reset' = 'earliest',
        'properties.request.timeout.ms' = '120000',
        'properties.default.api.timeout.ms' = '120000',
        'properties.session.timeout.ms' = '45000',
        'properties.heartbeat.interval.ms' = '15000',
        'format' = 'json',
        'json.ignore-parse-errors' = 'true',
        'json.fail-on-missing-field' = 'false'
      )"
    ],
    execution_config={
      'pipeline.name': 'dbt-nsi-contractor',
      'execution.checkpointing.interval': '300s',
      'execution.checkpointing.mode': 'EXACTLY_ONCE',
      'execution.checkpointing.min-pause': '30s',
      'execution.checkpointing.timeout': '600s',
      'execution.checkpointing.max-concurrent-checkpoints': '1',
      'execution.checkpointing.externalized-checkpoint-retention': 'RETAIN_ON_CANCELLATION',
      'state.backend': 'hashmap',
      'state.checkpoints.num-retained': '2',
      'state.checkpoints.dir': 's3://flink/checkpoints/dbt-nsi-contractor'
    },
    connector_properties=iceberg_connector_properties('rzdm__nsi')
  )
}}

SELECT
    {{ empty_to_null('`ВерсияДанных`') }} AS `ВерсияДанных`,
    {{ bool_to_boolean('`DeletionMark`') }} AS `DeletionMark`,
    {{ empty_to_null('`UID`') }} AS `UID`,
    {{ empty_to_null('`GUID`') }} AS `GUID`,
    {{ empty_to_null('`Name`') }} AS `Name`,
    {{ empty_to_null('`Code`') }} AS `Code`,
    {{ empty_to_null('`Parent`') }} AS `Parent`,
    {{ bool_to_boolean('`IsGroupe`') }} AS `IsGroupe`,
    {{ empty_to_null('`rc_AdresMezhdunarodnyy`') }} AS `rc_AdresMezhdunarodnyy`,
    {{ empty_to_null(onec_value('`rc_VidGosudarstvennogoOrgana`')) }} AS `rc_VidGosudarstvennogoOrgana`,
    {{ empty_to_null(onec_value('`rc_VidKontragentaDlyaVGO`')) }} AS `rc_VidKontragentaDlyaVGO`,
    {{ empty_to_null('`rc_GorodStranaMezhdunarodnyy`') }} AS `rc_GorodStranaMezhdunarodnyy`,
    {{ bool_to_boolean('`rc_GosudarstvennyyOrgan`') }} AS `rc_GosudarstvennyyOrgan`,
    {{ empty_to_null('`rc_GruppaKontragenta`') }} AS `rc_GruppaKontragenta`,
    {{ safe_timestamp3('`rc_DataPostanovkiNaUchetVNalogovoy`') }} AS `rc_DataPostanovkiNaUchetVNalogovoy`,
    {{ safe_timestamp3('`rc_DataRozhdeniya`') }} AS `rc_DataRozhdeniya`,
    {{ empty_to_null('`rc_DULNomer`') }} AS `rc_DULNomer`,
    {{ empty_to_null('`rc_DULSeriya`') }} AS `rc_DULSeriya`,
    {{ empty_to_null('`rc_Imya`') }} AS `rc_Imya`,
    {{ bool_to_boolean('`rc_IndividualnyyPredprinimatel`') }} AS `rc_IndividualnyyPredprinimatel`,
    {{ bool_to_boolean('`rc_IspolzovatProgrammuZakupok`') }} AS `rc_IspolzovatProgrammuZakupok`,
    {{ empty_to_null('`rc_KanalProdazh`') }} AS `rc_KanalProdazh`,
    {{ empty_to_null('`rc_KodGosudarstvennogoOrgana`') }} AS `rc_KodGosudarstvennogoOrgana`,
    {{ empty_to_null('`rc_KodOKVED`') }} AS `rc_KodOKVED`,
    {{ empty_to_null('`rc_KodOKVED2`') }} AS `rc_KodOKVED2`,
    {{ empty_to_null('`rc_KodOKFS`') }} AS `rc_KodOKFS`,
    {{ empty_to_null('`rc_KodPoOKTMO`') }} AS `rc_KodPoOKTMO`,
    {{ empty_to_null('`rc_OsnovnoeKontaktnoeLitso`') }} AS `rc_OsnovnoeKontaktnoeLitso`,
    {{ empty_to_null('`rc_OsnovnoeKontaktnoeLitsoVIFNS`') }} AS `rc_OsnovnoeKontaktnoeLitsoVIFNS`,
    {{ empty_to_null('`rc_OsnovnoyBankovskiySchet`') }} AS `rc_OsnovnoyBankovskiySchet`,
    {{ empty_to_null('`rc_Otchestvo`') }} AS `rc_Otchestvo`,
    {{ empty_to_null('`rc_PodrazdeleniePoOrgShtatnoyStrukture`') }} AS `rc_PodrazdeleniePoOrgShtatnoyStrukture`,
    {{ empty_to_null('`rc_PodrazdeleniePoUpravlencheskoyStrukture`') }} AS `rc_PodrazdeleniePoUpravlencheskoyStrukture`,
    {{ empty_to_null(onec_value('`rc_Pol`')) }} AS `rc_Pol`,
    {{ bool_to_boolean('`rc_PriznakMeditsinskoyOrganizatsii`') }} AS `rc_PriznakMeditsinskoyOrganizatsii`,
    {{ bool_to_boolean('`rc_Samozanyatyy`') }} AS `rc_Samozanyatyy`,
    {{ safe_timestamp3('`rc_SvidetelstvoDataVydachi`') }} AS `rc_SvidetelstvoDataVydachi`,
    {{ empty_to_null('`rc_SvidetelstvoSeriyaNomer`') }} AS `rc_SvidetelstvoSeriyaNomer`,
    {{ empty_to_null('`rc_SNILS`') }} AS `rc_SNILS`,
    {{ bool_to_boolean('`rc_SubektMalogoIliSrednegoPredprinimatelstvaUKh`') }} AS `rc_SubektMalogoIliSrednegoPredprinimatelstvaUKh`,
    {{ empty_to_null('`rc_Familiya`') }} AS `rc_Familiya`,
    {{ empty_to_null('`rc_FIOIDolzhnostRukovoditelya`') }} AS `rc_FIOIDolzhnostRukovoditelya`,
    {{ empty_to_null('`rc_FIOIDolzhnostRukovoditelyaVRoditelnomPadezhe`') }} AS `rc_FIOIDolzhnostRukovoditelyaVRoditelnomPadezhe`,
    {{ bool_to_boolean('`rc_FormaUchastiyaVKapitale`') }} AS `rc_FormaUchastiyaVKapitale`,
    {{ bool_to_boolean('`rc_EtoBank`') }} AS `rc_EtoBank`,
    {{ bool_to_boolean('`rc_EtoStrakhovayaKompaniya`') }} AS `rc_EtoStrakhovayaKompaniya`,
    {{ empty_to_null(onec_value('`rc_YuridicheskoeFizicheskoeLitso`')) }} AS `rc_YuridicheskoeFizicheskoeLitso`,
    {{ empty_to_null('`GolovnoyKontragent`') }} AS `GolovnoyKontragent`,
    {{ empty_to_null('`DokumentUdostoveryayushchiyLichnost`') }} AS `DokumentUdostoveryayushchiyLichnost`,
    {{ empty_to_null('`Identifikator`') }} AS `Identifikator`,
    {{ empty_to_null('`INN`') }} AS `INN`,
    {{ empty_to_null('`KodOKOPF`') }} AS `KodOKOPF`,
    {{ empty_to_null('`KodPoOKPO`') }} AS `KodPoOKPO`,
    {{ empty_to_null('`Kommentariy`') }} AS `Kommentariy`,
    {{ empty_to_null('`KPP`') }} AS `KPP`,
    {{ empty_to_null('`MezhdunarodnoeNaimenovanie`') }} AS `MezhdunarodnoeNaimenovanie`,
    {{ empty_to_null('`NaborSvoystv`') }} AS `NaborSvoystv`,
    {{ empty_to_null('`NaimenovanieOKOPF`') }} AS `NaimenovanieOKOPF`,
    {{ empty_to_null('`NalogovyyNomer`') }} AS `NalogovyyNomer`,
    {{ bool_to_boolean('`Nerezident`') }} AS `Nerezident`,
    {{ bool_to_boolean('`ObosoblennoePodrazdelenie`') }} AS `ObosoblennoePodrazdelenie`,
    {{ empty_to_null('`OGRN`') }} AS `OGRN`,
    {{ empty_to_null('`OKDP`') }} AS `OKDP`,
    {{ empty_to_null('`Opisanie`') }} AS `Opisanie`,
    {{ empty_to_null('`OrganizatsionnayaEdinitsa`') }} AS `OrganizatsionnayaEdinitsa`,
    {{ empty_to_null('`OrganizatsionnoPravovayaForma`') }} AS `OrganizatsionnoPravovayaForma`,
    {{ empty_to_null('`Partner`') }} AS `Partner`,
    {{ empty_to_null('`PolnoeNaimenovanie`') }} AS `PolnoeNaimenovanie`,
    {{ empty_to_null(onec_value('`PriznakIspolzovaniya`')) }} AS `PriznakIspolzovaniya`,
    {{ empty_to_null('`RegistratsionnyyNomerNerezidenta`') }} AS `RegistratsionnyyNomerNerezidenta`,
    {{ empty_to_null('`SokrashchennoeNaimenovanie`') }} AS `SokrashchennoeNaimenovanie`,
    {{ empty_to_null('`StranaRegistratsii`') }} AS `StranaRegistratsii`,
    {{ bool_to_boolean('`UdalitZapisNeNormalizuema`') }} AS `UdalitZapisNeNormalizuema`,
    {{ empty_to_null(onec_value('`UdalitTipPozitsii`')) }} AS `UdalitTipPozitsii`,
    {{ empty_to_null('`UdalitEtalonnayaPozitsiya`') }} AS `UdalitEtalonnayaPozitsiya`,
    {{ bool_to_boolean('`UdalitEtoMaket`') }} AS `UdalitEtoMaket`,
    {{ empty_to_null(onec_value('`YurFizLitso`')) }} AS `YurFizLitso`,
    {{ empty_to_null('`OsnovnoyBankovskiySchet`') }} AS `OsnovnoyBankovskiySchet`,
    TRY_CAST(`Version` AS BIGINT) AS `Version`,
    {{ safe_timestamp3('`VersionDate`') }} AS `VersionDate`,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) AS load_dttm,
    CAST(NULL AS TIMESTAMP(3)) AS load_dttm_tz,
    CAST(NULL AS BIGINT) AS load_id,
    'nsi' AS src_system_code,
    CAST(NULL AS STRING) AS etl_batch_id,
    {{ safe_timestamp3('`extract_timestamp`') }} AS extract_dttm,
    NULLIF(`operation_type`, '') AS src_dml_type,
    {{ safe_timestamp3('`src_change_timestamp`') }} AS src_chng_dttm
FROM default_catalog.default_database.contractor_source
