{{
  config(
    materialized='table',
    type='streaming',
    pre_hook=[
      "DROP TABLE IF EXISTS default_catalog.default_database.organization_source",
      "CREATE TABLE default_catalog.default_database.organization_source (
        `GUID` VARCHAR(50),
        `INN` STRING,
        `KPP` STRING,
        `UID` VARCHAR(50),
        `Name` STRING,
        `Code` STRING,
        `Parent` STRING,
        `IsGroupe` STRING,
        `DeletionMark` STRING,
        `IndividualnyyPredprinimatel` STRING,
        `rc_Audit` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_Auditor` STRING,
        `rc_VidInostrannoyStruktury` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_VidOrganizatsiiPoUmolchaniyu` STRING,
        `rc_VidOtkloneniyaKontroliruemogoZnacheniya` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_GlavnyyBukhgalterFIO` STRING,
        `rc_GorodStranaMezhdunarodnyy` STRING,
        `rc_GruppaKontragenta` STRING,
        `rc_DataPrekrashcheniyaDeyatelnosti` STRING,
        `rc_Divizion` STRING,
        `rc_ZakupkaPoFZ223` STRING,
        `rc_InostrannayaStrukturaBezObrazovaniyaYurLitsa` STRING,
        `rc_InostrannyyNalogovyyRezident` STRING,
        `rc_IPImya` STRING,
        `rc_IPOtchestvo` STRING,
        `rc_IPFamiliya` STRING,
        `rc_IspolzovatStrokuPlanaZakupok` STRING,
        `rc_KodInykhVidovDeyatelnostiNFO` STRING,
        `rc_KodNalogoplatelshchikaInostrannyy` STRING,
        `rc_KodOsnovnogoVidaDeyatelnostiNFO` STRING,
        `rc_Makroregion` STRING,
        `rc_NaimenovanieBE` STRING,
        `rc_NaimenovanieInykhVidovDeyatelnostiNFO` STRING,
        `rc_NaimenovanieOrganizatsiiNaAngliyskomYazyke` STRING,
        `rc_NaimenovanieOsnovnogoVidaDeyatelnostiNFO` STRING,
        `rc_NaimenovanieRegistriruyushchegoOrgana` STRING,
        `rc_NekreditnayaFinansovayaOrganizatsiya` STRING,
        `rc_OrganizatsiyaDeystvuyushchaya` STRING,
        `rc_OsnovaniePrekrashcheniyaDeyatelnosti` STRING,
        `rc_OsnovnoyBankovskiySchet` STRING,
        `rc_PoligonZhD` STRING,
        `rc_RegionRossii` STRING,
        `rc_RegistriruyushchiyOrgan` STRING,
        `rc_RukovoditelOrganizatsiiDolzhnost` STRING,
        `rc_RukovoditelOrganizatsiiFIO` STRING,
        `rc_SvedeniyaOLitsenzii` STRING,
        `rc_TarifnayaZona` STRING,
        `rc_TipElementa` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_FormatTsFO` STRING,
        `rc_FRMO_OrgID` STRING,
        `rc_EtoBank` STRING,
        `rc_EtoIndividualnyyPredprinimatel` STRING,
        `rc_EtoMezhdunarodnyyKholding` STRING,
        `rc_EtoNKO` STRING,
        `rc_EtoSamozanyatyy` STRING,
        `rc_EtoStrakhovayaKompaniya` STRING,
        `rc_AdresMezhdunarodnyy` STRING,
        `rc_KodOKVED2` STRING,
        `VidObmenaSKontroliruyushchimiOrganami` ROW<`Тип1С` STRING, `Значение` STRING>,
        `Voenkomat` STRING,
        `ValyutaReglamentirovannogoUcheta` STRING,
        `GrafikRaboty` STRING,
        `DataRegistratsii` STRING,
        `DopolnitelnyyKodFSS` STRING,
        `DopuskayutsyaVzaimoraschetyCherezGolovnuyuOrganizatsiyu` STRING,
        `EstObosoblennyePodrazdeleniya` STRING,
        `ZaregistrirovanVOEZ` STRING,
        `IPKodPodchinennostiFSS` STRING,
        `IPRegistratsionnyyNomerPFR` STRING,
        `IPRegistratsionnyyNomerTFOMS` STRING,
        `IPRegistratsionnyyNomerFSS` STRING,
        `KodVStraneRegistratsii` STRING,
        `KodNalogovogoOrgana` STRING,
        `KodNalogovogoOrganaPoluchatelya` STRING,
        `KodOKVED` STRING,
        `KodOKVED2` STRING,
        `KodOKOPF` STRING,
        `KodOKFS` STRING,
        `KodOrganaPFR` STRING,
        `KodOrganaFSGS` STRING,
        `KodPodchinennostiFSS` STRING,
        `KodPoOKATO` STRING,
        `KodPoOKPO` STRING,
        `Kontragent` STRING,
        `NaimenovanieSokrashchennoe` STRING,
        `KrupneyshiyNalogoplatelshchik` STRING,
        `NaborSvoystv` STRING,
        `NaimenovanieInostrOrganizatsii` STRING,
        `OGRN` STRING,
        `NaimenovanieNalogovogoOrgana` STRING,
        `Prefiks` STRING,
        `NaimenovanieTerritorialnogoOrganaPFR` VARCHAR(1048576),
        `NaimenovanieTerritorialnogoOrganaFSS` STRING,
        `NeZapolnyatPodrazdeleniyaVMeropriyatiyakhTrudovoyD` STRING,
        `ObmenKatalogOtpravkiDannykhOtchetnosti` STRING,
        `ObmenKatalogProgrammyElektronnoyPochty` STRING,
        `ObmenKodAbonenta` STRING,
        `ObosoblennoePodrazdelenie` STRING,
        `GolovnayaOrganizatsiya` STRING,
        `OtdelenieInostrannoyOrganizatsii` STRING,
        `PolnoeNaimenovanie` STRING,
        `NaimenovanieMezhdunarodnoe` STRING,
        `PrimenyatRayonnyyKoeffitsient` STRING,
        `PrimenyatSevernuyuNadbavku` STRING,
        `ProtsentSevernoyNadbavki` DECIMAL(9,2),
        `RayonnyyKoeffitsient` DECIMAL(9,2),
        `RayonnyyKoeffitsientRF` DECIMAL(9,2),
        `RegistratsionnyyNomerPFR` STRING,
        `RegistratsionnyyNomerTFOMS` STRING,
        `RegistratsionnyyNomerFSS` STRING,
        `RegistratsiyaVNalogovomOrgane` STRING,
        `SvidetelstvoDataVydachi` STRING,
        `SvidetelstvoSeriyaNomer` STRING,
        `StranaPostoyannogoMestonakhozhdeniya` STRING,
        `StranaRegistratsii` STRING,
        `StranaRegistratsiiInostrannoyOrganizatsii` STRING,
        `UchetnayaZapisObmena` STRING,
        `FaylLogotip` STRING,
        `FaylFaksimilnayaPechat` STRING,
        `TsifrovoyIndeksObosoblennogoPodrazdeleniya` DECIMAL(9,2),
        `YuridicheskoeFizicheskoeLitso` ROW<`Тип1С` STRING, `Значение` STRING>,
        `YurFizLitso` ROW<`Тип1С` STRING, `Значение` STRING>,
        `rc_NaimenovanieOKVED2` STRING,
        `rc_KodOKTMO` STRING,
        `rc_NaimenovanieOKVED` STRING,
        `rc_NaimenovanieOKOPF` STRING,
        `rc_NaimenovanieOKFS` STRING,
        `src_change_timestamp` STRING,
        `extract_timestamp` STRING,
        `operation_type` STRING,
        `Version` VARCHAR(10),
        `VersionDate` STRING
      ) WITH (
        'connector' = 'kafka',
        'topic' = 'sys__nsi__esud_rzdm__organization__data',
        'properties.bootstrap.servers' = '{{ kafka_bootstrap_servers() }}',
        'properties.security.protocol' = '{{ kafka_security_protocol() }}',
        'properties.sasl.mechanism' = '{{ kafka_sasl_mechanism() }}',
        'properties.sasl.jaas.config' = '{{ kafka_sasl_jaas_config() }}',
        'properties.group.id' = 'dbt-nsi-organization',
        'scan.startup.mode' = 'group-offsets',
        'properties.auto.offset.reset' = 'earliest',
        'properties.request.timeout.ms' = '120000',
        'properties.default.api.timeout.ms' = '120000',
        'properties.session.timeout.ms' = '45000',
        'properties.heartbeat.interval.ms' = '15000',
        'format' = 'json',
        'json.ignore-parse-errors' = 'true',
        'json.fail-on-missing-field' = 'false'
      )"
    ],
    execution_config={
      'pipeline.name': 'dbt-nsi-organization',
      'execution.checkpointing.interval': '300s',
      'execution.checkpointing.mode': 'EXACTLY_ONCE',
      'execution.checkpointing.min-pause': '30s',
      'execution.checkpointing.timeout': '600s',
      'execution.checkpointing.max-concurrent-checkpoints': '1',
      'execution.checkpointing.externalized-checkpoint-retention': 'RETAIN_ON_CANCELLATION',
      'state.backend': 'hashmap',
      'state.checkpoints.num-retained': '2',
      'state.checkpoints.dir': 's3://flink/checkpoints/dbt-nsi-organization'
    },
    connector_properties=iceberg_connector_properties('rzdm__nsi')
  )
}}

SELECT
    {{ empty_to_null('`GUID`') }} AS `GUID`,
    {{ empty_to_null('`INN`') }} AS `INN`,
    {{ empty_to_null('`KPP`') }} AS `KPP`,
    {{ empty_to_null('`UID`') }} AS `UID`,
    {{ empty_to_null('`Name`') }} AS `Name`,
    {{ empty_to_null('`Code`') }} AS `Code`,
    {{ empty_to_null('`Parent`') }} AS `Parent`,
    {{ bool_to_boolean('`IsGroupe`') }} AS `IsGroupe`,
    {{ bool_to_boolean('`DeletionMark`') }} AS `DeletionMark`,
    {{ empty_to_null('`IndividualnyyPredprinimatel`') }} AS `IndividualnyyPredprinimatel`,
    {{ empty_to_null(onec_value('`rc_Audit`')) }} AS `rc_Audit`,
    {{ empty_to_null('`rc_Auditor`') }} AS `rc_Auditor`,
    {{ empty_to_null(onec_value('`rc_VidInostrannoyStruktury`')) }} AS `rc_VidInostrannoyStruktury`,
    {{ empty_to_null('`rc_VidOrganizatsiiPoUmolchaniyu`') }} AS `rc_VidOrganizatsiiPoUmolchaniyu`,
    {{ empty_to_null(onec_value('`rc_VidOtkloneniyaKontroliruemogoZnacheniya`')) }} AS `rc_VidOtkloneniyaKontroliruemogoZnacheniya`,
    {{ empty_to_null('`rc_GlavnyyBukhgalterFIO`') }} AS `rc_GlavnyyBukhgalterFIO`,
    {{ empty_to_null('`rc_GorodStranaMezhdunarodnyy`') }} AS `rc_GorodStranaMezhdunarodnyy`,
    {{ empty_to_null('`rc_GruppaKontragenta`') }} AS `rc_GruppaKontragenta`,
    {{ safe_timestamp3('`rc_DataPrekrashcheniyaDeyatelnosti`') }} AS `rc_DataPrekrashcheniyaDeyatelnosti`,
    {{ empty_to_null('`rc_Divizion`') }} AS `rc_Divizion`,
    {{ bool_to_boolean('`rc_ZakupkaPoFZ223`') }} AS `rc_ZakupkaPoFZ223`,
    {{ bool_to_boolean('`rc_InostrannayaStrukturaBezObrazovaniyaYurLitsa`') }} AS `rc_InostrannayaStrukturaBezObrazovaniyaYurLitsa`,
    {{ bool_to_boolean('`rc_InostrannyyNalogovyyRezident`') }} AS `rc_InostrannyyNalogovyyRezident`,
    {{ empty_to_null('`rc_IPImya`') }} AS `rc_IPImya`,
    {{ empty_to_null('`rc_IPOtchestvo`') }} AS `rc_IPOtchestvo`,
    {{ empty_to_null('`rc_IPFamiliya`') }} AS `rc_IPFamiliya`,
    {{ bool_to_boolean('`rc_IspolzovatStrokuPlanaZakupok`') }} AS `rc_IspolzovatStrokuPlanaZakupok`,
    {{ empty_to_null('`rc_KodInykhVidovDeyatelnostiNFO`') }} AS `rc_KodInykhVidovDeyatelnostiNFO`,
    {{ empty_to_null('`rc_KodNalogoplatelshchikaInostrannyy`') }} AS `rc_KodNalogoplatelshchikaInostrannyy`,
    {{ empty_to_null('`rc_KodOsnovnogoVidaDeyatelnostiNFO`') }} AS `rc_KodOsnovnogoVidaDeyatelnostiNFO`,
    {{ empty_to_null('`rc_Makroregion`') }} AS `rc_Makroregion`,
    {{ empty_to_null('`rc_NaimenovanieBE`') }} AS `rc_NaimenovanieBE`,
    {{ empty_to_null('`rc_NaimenovanieInykhVidovDeyatelnostiNFO`') }} AS `rc_NaimenovanieInykhVidovDeyatelnostiNFO`,
    {{ empty_to_null('`rc_NaimenovanieOrganizatsiiNaAngliyskomYazyke`') }} AS `rc_NaimenovanieOrganizatsiiNaAngliyskomYazyke`,
    {{ empty_to_null('`rc_NaimenovanieOsnovnogoVidaDeyatelnostiNFO`') }} AS `rc_NaimenovanieOsnovnogoVidaDeyatelnostiNFO`,
    {{ empty_to_null('`rc_NaimenovanieRegistriruyushchegoOrgana`') }} AS `rc_NaimenovanieRegistriruyushchegoOrgana`,
    {{ bool_to_boolean('`rc_NekreditnayaFinansovayaOrganizatsiya`') }} AS `rc_NekreditnayaFinansovayaOrganizatsiya`,
    {{ bool_to_boolean('`rc_OrganizatsiyaDeystvuyushchaya`') }} AS `rc_OrganizatsiyaDeystvuyushchaya`,
    {{ empty_to_null('`rc_OsnovaniePrekrashcheniyaDeyatelnosti`') }} AS `rc_OsnovaniePrekrashcheniyaDeyatelnosti`,
    {{ empty_to_null('`rc_OsnovnoyBankovskiySchet`') }} AS `rc_OsnovnoyBankovskiySchet`,
    {{ empty_to_null('`rc_PoligonZhD`') }} AS `rc_PoligonZhD`,
    {{ empty_to_null('`rc_RegionRossii`') }} AS `rc_RegionRossii`,
    {{ empty_to_null('`rc_RegistriruyushchiyOrgan`') }} AS `rc_RegistriruyushchiyOrgan`,
    {{ empty_to_null('`rc_RukovoditelOrganizatsiiDolzhnost`') }} AS `rc_RukovoditelOrganizatsiiDolzhnost`,
    {{ empty_to_null('`rc_RukovoditelOrganizatsiiFIO`') }} AS `rc_RukovoditelOrganizatsiiFIO`,
    {{ empty_to_null('`rc_SvedeniyaOLitsenzii`') }} AS `rc_SvedeniyaOLitsenzii`,
    {{ empty_to_null('`rc_TarifnayaZona`') }} AS `rc_TarifnayaZona`,
    {{ empty_to_null(onec_value('`rc_TipElementa`')) }} AS `rc_TipElementa`,
    {{ empty_to_null('`rc_FormatTsFO`') }} AS `rc_FormatTsFO`,
    {{ empty_to_null('`rc_FRMO_OrgID`') }} AS `rc_FRMO_OrgID`,
    {{ bool_to_boolean('`rc_EtoBank`') }} AS `rc_EtoBank`,
    {{ bool_to_boolean('`rc_EtoIndividualnyyPredprinimatel`') }} AS `rc_EtoIndividualnyyPredprinimatel`,
    {{ bool_to_boolean('`rc_EtoMezhdunarodnyyKholding`') }} AS `rc_EtoMezhdunarodnyyKholding`,
    {{ bool_to_boolean('`rc_EtoNKO`') }} AS `rc_EtoNKO`,
    {{ bool_to_boolean('`rc_EtoSamozanyatyy`') }} AS `rc_EtoSamozanyatyy`,
    {{ bool_to_boolean('`rc_EtoStrakhovayaKompaniya`') }} AS `rc_EtoStrakhovayaKompaniya`,
    {{ empty_to_null('`rc_AdresMezhdunarodnyy`') }} AS `rc_AdresMezhdunarodnyy`,
    {{ empty_to_null('`rc_KodOKVED2`') }} AS `rc_KodOKVED2`,
    {{ empty_to_null(onec_value('`VidObmenaSKontroliruyushchimiOrganami`')) }} AS `VidObmenaSKontroliruyushchimiOrganami`,
    {{ empty_to_null('`Voenkomat`') }} AS `Voenkomat`,
    {{ empty_to_null('`ValyutaReglamentirovannogoUcheta`') }} AS `ValyutaReglamentirovannogoUcheta`,
    {{ empty_to_null('`GrafikRaboty`') }} AS `GrafikRaboty`,
    {{ safe_timestamp3('`DataRegistratsii`') }} AS `DataRegistratsii`,
    {{ empty_to_null('`DopolnitelnyyKodFSS`') }} AS `DopolnitelnyyKodFSS`,
    {{ bool_to_boolean('`DopuskayutsyaVzaimoraschetyCherezGolovnuyuOrganizatsiyu`') }} AS `DopuskayutsyaVzaimoraschetyCherezGolovnuyuOrganizatsiyu`,
    {{ bool_to_boolean('`EstObosoblennyePodrazdeleniya`') }} AS `EstObosoblennyePodrazdeleniya`,
    {{ bool_to_boolean('`ZaregistrirovanVOEZ`') }} AS `ZaregistrirovanVOEZ`,
    {{ empty_to_null('`IPKodPodchinennostiFSS`') }} AS `IPKodPodchinennostiFSS`,
    {{ empty_to_null('`IPRegistratsionnyyNomerPFR`') }} AS `IPRegistratsionnyyNomerPFR`,
    {{ empty_to_null('`IPRegistratsionnyyNomerTFOMS`') }} AS `IPRegistratsionnyyNomerTFOMS`,
    {{ empty_to_null('`IPRegistratsionnyyNomerFSS`') }} AS `IPRegistratsionnyyNomerFSS`,
    {{ empty_to_null('`KodVStraneRegistratsii`') }} AS `KodVStraneRegistratsii`,
    {{ empty_to_null('`KodNalogovogoOrgana`') }} AS `KodNalogovogoOrgana`,
    {{ empty_to_null('`KodNalogovogoOrganaPoluchatelya`') }} AS `KodNalogovogoOrganaPoluchatelya`,
    {{ empty_to_null('`KodOKVED`') }} AS `KodOKVED`,
    {{ empty_to_null('`KodOKVED2`') }} AS `KodOKVED2`,
    {{ empty_to_null('`KodOKOPF`') }} AS `KodOKOPF`,
    {{ empty_to_null('`KodOKFS`') }} AS `KodOKFS`,
    {{ empty_to_null('`KodOrganaPFR`') }} AS `KodOrganaPFR`,
    {{ empty_to_null('`KodOrganaFSGS`') }} AS `KodOrganaFSGS`,
    {{ empty_to_null('`KodPodchinennostiFSS`') }} AS `KodPodchinennostiFSS`,
    {{ empty_to_null('`KodPoOKATO`') }} AS `KodPoOKATO`,
    {{ empty_to_null('`KodPoOKPO`') }} AS `KodPoOKPO`,
    {{ empty_to_null('`Kontragent`') }} AS `Kontragent`,
    {{ empty_to_null('`NaimenovanieSokrashchennoe`') }} AS `NaimenovanieSokrashchennoe`,
    {{ bool_to_boolean('`KrupneyshiyNalogoplatelshchik`') }} AS `KrupneyshiyNalogoplatelshchik`,
    {{ empty_to_null('`NaborSvoystv`') }} AS `NaborSvoystv`,
    {{ empty_to_null('`NaimenovanieInostrOrganizatsii`') }} AS `NaimenovanieInostrOrganizatsii`,
    {{ empty_to_null('`OGRN`') }} AS `OGRN`,
    {{ empty_to_null('`NaimenovanieNalogovogoOrgana`') }} AS `NaimenovanieNalogovogoOrgana`,
    {{ empty_to_null('`Prefiks`') }} AS `Prefiks`,
    {{ empty_to_null('`NaimenovanieTerritorialnogoOrganaPFR`') }} AS `NaimenovanieTerritorialnogoOrganaPFR`,
    {{ empty_to_null('`NaimenovanieTerritorialnogoOrganaFSS`') }} AS `NaimenovanieTerritorialnogoOrganaFSS`,
    {{ bool_to_boolean('`NeZapolnyatPodrazdeleniyaVMeropriyatiyakhTrudovoyD`') }} AS `NeZapolnyatPodrazdeleniyaVMeropriyatiyakhTrudovoyD`,
    {{ empty_to_null('`ObmenKatalogOtpravkiDannykhOtchetnosti`') }} AS `ObmenKatalogOtpravkiDannykhOtchetnosti`,
    {{ empty_to_null('`ObmenKatalogProgrammyElektronnoyPochty`') }} AS `ObmenKatalogProgrammyElektronnoyPochty`,
    {{ empty_to_null('`ObmenKodAbonenta`') }} AS `ObmenKodAbonenta`,
    {{ bool_to_boolean('`ObosoblennoePodrazdelenie`') }} AS `ObosoblennoePodrazdelenie`,
    {{ empty_to_null('`GolovnayaOrganizatsiya`') }} AS `GolovnayaOrganizatsiya`,
    {{ bool_to_boolean('`OtdelenieInostrannoyOrganizatsii`') }} AS `OtdelenieInostrannoyOrganizatsii`,
    {{ empty_to_null('`PolnoeNaimenovanie`') }} AS `PolnoeNaimenovanie`,
    {{ empty_to_null('`NaimenovanieMezhdunarodnoe`') }} AS `NaimenovanieMezhdunarodnoe`,
    {{ bool_to_boolean('`PrimenyatRayonnyyKoeffitsient`') }} AS `PrimenyatRayonnyyKoeffitsient`,
    {{ bool_to_boolean('`PrimenyatSevernuyuNadbavku`') }} AS `PrimenyatSevernuyuNadbavku`,
    `ProtsentSevernoyNadbavki` AS `ProtsentSevernoyNadbavki`,
    `RayonnyyKoeffitsient` AS `RayonnyyKoeffitsient`,
    `RayonnyyKoeffitsientRF` AS `RayonnyyKoeffitsientRF`,
    {{ empty_to_null('`RegistratsionnyyNomerPFR`') }} AS `RegistratsionnyyNomerPFR`,
    {{ empty_to_null('`RegistratsionnyyNomerTFOMS`') }} AS `RegistratsionnyyNomerTFOMS`,
    {{ empty_to_null('`RegistratsionnyyNomerFSS`') }} AS `RegistratsionnyyNomerFSS`,
    {{ empty_to_null('`RegistratsiyaVNalogovomOrgane`') }} AS `RegistratsiyaVNalogovomOrgane`,
    {{ safe_timestamp3('`SvidetelstvoDataVydachi`') }} AS `SvidetelstvoDataVydachi`,
    {{ empty_to_null('`SvidetelstvoSeriyaNomer`') }} AS `SvidetelstvoSeriyaNomer`,
    {{ empty_to_null('`StranaPostoyannogoMestonakhozhdeniya`') }} AS `StranaPostoyannogoMestonakhozhdeniya`,
    {{ empty_to_null('`StranaRegistratsii`') }} AS `StranaRegistratsii`,
    {{ empty_to_null('`StranaRegistratsiiInostrannoyOrganizatsii`') }} AS `StranaRegistratsiiInostrannoyOrganizatsii`,
    {{ empty_to_null('`UchetnayaZapisObmena`') }} AS `UchetnayaZapisObmena`,
    {{ empty_to_null('`FaylLogotip`') }} AS `FaylLogotip`,
    {{ empty_to_null('`FaylFaksimilnayaPechat`') }} AS `FaylFaksimilnayaPechat`,
    `TsifrovoyIndeksObosoblennogoPodrazdeleniya` AS `TsifrovoyIndeksObosoblennogoPodrazdeleniya`,
    {{ empty_to_null(onec_value('`YuridicheskoeFizicheskoeLitso`')) }} AS `YuridicheskoeFizicheskoeLitso`,
    {{ empty_to_null(onec_value('`YurFizLitso`')) }} AS `YurFizLitso`,
    {{ empty_to_null('`rc_NaimenovanieOKVED2`') }} AS `rc_NaimenovanieOKVED2`,
    {{ empty_to_null('`rc_KodOKTMO`') }} AS `rc_KodOKTMO`,
    {{ empty_to_null('`rc_NaimenovanieOKVED`') }} AS `rc_NaimenovanieOKVED`,
    {{ empty_to_null('`rc_NaimenovanieOKOPF`') }} AS `rc_NaimenovanieOKOPF`,
    {{ empty_to_null('`rc_NaimenovanieOKFS`') }} AS `rc_NaimenovanieOKFS`,
    {{ empty_to_null('`Version`') }} AS `Version`,
    {{ safe_timestamp3('`VersionDate`') }} AS `VersionDate`,
    CAST(CURRENT_TIMESTAMP AS TIMESTAMP(3)) AS load_dttm,
    CAST(NULL AS TIMESTAMP(3)) AS load_dttm_tz,
    CAST(NULL AS BIGINT) AS load_id,
    'nsi' AS src_system_code,
    CAST(NULL AS STRING) AS etl_batch_id,
    {{ safe_timestamp3('`extract_timestamp`') }} AS `extract_dttm`,
    NULLIF(`operation_type`, '') AS src_dml_type,
    {{ safe_timestamp3('`src_change_timestamp`') }} AS `src_chng_dttm`
FROM default_catalog.default_database.organization_source
