name: 'nsi_streaming_project'
version: '1.0.0'
config-version: 2

profile: 'flink_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  nsi_streaming_project:
    +materialized: table
